-- DROP TABLES IF THEY EXIST
IF OBJECT_ID('dbo.ALL_USER','U') IS NOT NULL
    DROP TABLE dbo.ALL_USER;
IF OBJECT_ID('dbo.CLIENTES','U') IS NOT NULL
    DROP TABLE dbo.CLIENTES;
IF OBJECT_ID('dbo.COMPONENTES_MECATRAFI','U') IS NOT NULL
    DROP TABLE dbo.COMPONENTES_MECATRAFI;
IF OBJECT_ID('dbo.FAJAS','U') IS NOT NULL
    DROP TABLE dbo.FAJAS;
IF OBJECT_ID('dbo.POLEAS','U') IS NOT NULL
    DROP TABLE dbo.POLEAS;
IF OBJECT_ID('dbo.TORNILLOS','U') IS NOT NULL
    DROP TABLE dbo.TORNILLOS;
IF OBJECT_ID('dbo.MOTORESAC','U') IS NOT NULL
    DROP TABLE dbo.MOTORESAC;
IF OBJECT_ID('dbo.MOTORESDC','U') IS NOT NULL
    DROP TABLE dbo.MOTORESDC;
IF OBJECT_ID('dbo.PROPERTY_COMPONENTES_MECATRAFI','U') IS NOT NULL
    DROP TABLE dbo.PROPERTY_COMPONENTES_MECATRAFI;
IF OBJECT_ID('dbo.MECATRAFI_ORDER','U') IS NOT NULL
    DROP TABLE dbo.MECATRAFI_ORDER;
IF OBJECT_ID('dbo.ORDER_COMPONENTE','U') IS NOT NULL
    DROP TABLE dbo.ORDER_COMPONENTE;
IF OBJECT_ID('dbo.SALE','U') IS NOT NULL
    DROP TABLE dbo.SALE;

-- CREATE TABLES
CREATE TABLE ALL_USER (
    CODIGO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    STATUS CHAR(1) NULL,
    USER_TYPE CHAR(1) NOT NULL, -- 1: Manager, 2: Employee, 3: Cliente
    QUOTA DECIMAL(10,2) NULL,
    SPECIALTY VARCHAR(100) NULL,
    TELEFONO INT NOT NULL,
    PHOTO IMAGE NULL
);

CREATE TABLE CLIENTES (
    CODIGO VARCHAR(100) NOT NULL PRIMARY KEY, 
    CARRERA VARCHAR(200) NOT NULL,
    TELEFONO INT NOT NULL,
    PHOTO IMAGE NULL,
    NAME VARCHAR(200) NOT NULL
);

CREATE TABLE COMPONENTES_MECATRAFI ( 
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(200) NOT NULL,
    TIPO VARCHAR(100),
    CANTIDAD VARCHAR(400),
    PROVEEDOR VARCHAR(100)
);

CREATE TABLE FAJAS (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(200) NOT NULL,
    CANTIDAD VARCHAR(400),
    PROVEEDOR VARCHAR(100), 
    ALTO_GOMA DECIMAL(10,2),
    DIAMETRO_INTERNO DECIMAL(10,2),
    DIAMETRO_EXTERNO DECIMAL(10,2)
);

CREATE TABLE POLEAS (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(200) NOT NULL,
    CANTIDAD VARCHAR(400),
    PROVEEDOR VARCHAR(100),
    DIAMETRO_INTERNO DECIMAL(10,2),
    DIAMETRO_EXTERNO DECIMAL(10,2)
);

CREATE TABLE TORNILLOS (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(200) NOT NULL,
    CANTIDAD VARCHAR(400),
    PROVEEDOR VARCHAR(100),
    TIPO_PUNTA VARCHAR(100), 
    TIPO_ROSCA VARCHAR(100)
);

CREATE TABLE MOTORESAC (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(200) NOT NULL,
    CANTIDAD VARCHAR(400),
    PROVEEDOR VARCHAR(100),
    FRAME DECIMAL(10,2),
    POTENCIA DECIMAL(10,2),
    FASES VARCHAR(100)
);

CREATE TABLE MOTORESDC (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(200) NOT NULL,
    CANTIDAD VARCHAR(400),
    PROVEEDOR VARCHAR(100),
    VOLTAJE DECIMAL(10,2),
    POTENCIA DECIMAL(10,2),
    VELOCIDAD DECIMAL(10,2)
);

CREATE TABLE MECATRAFI_ORDER (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ORDER_DATE DATETIME,
    TABLE_NUMBER INT,
    TOTAL_AMOUNT DECIMAL(10,2),    
    CUSTOMER_ID INT,
    STATUS CHAR(1)
);

CREATE TABLE ORDER_COMPONENTE (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    ORDER_ID INT,
    COMPONENTE_ID INT,
    CANTIDAD INT,
    SUBTOTAL DECIMAL(10,2)
);

CREATE TABLE SALE (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    TAX DECIMAL(10,2),
    TOTAL_AMOUNT_WITHOUT_TAX DECIMAL(10,2),
    TOTAL_AMOUNT_WITH_TAX DECIMAL(10,2),
    ORDER_ID INT
);
GO

-- PROCEDURES FOR CLIENTES
IF OBJECT_ID('dbo.usp_AddClientes', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AddClientes;
GO
CREATE PROCEDURE usp_AddClientes(
    @NAME VARCHAR(200),
    @CARRERA VARCHAR(200),
    @TELEFONO INT,
    @PHOTO IMAGE,
    @CODIGO VARCHAR(100)
) AS
BEGIN
    INSERT INTO CLIENTES (CODIGO, CARRERA, TELEFONO, PHOTO, NAME)
    VALUES (@CODIGO, @CARRERA, @TELEFONO, @PHOTO, @NAME);
END
GO

IF OBJECT_ID('dbo.usp_UpdateClientes', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_UpdateClientes;
GO
CREATE PROCEDURE usp_UpdateClientes(
    @CODIGO VARCHAR(100),
    @NAME VARCHAR(200),
    @CARRERA VARCHAR(100),
    @TELEFONO INT,
    @PHOTO IMAGE
) AS
BEGIN
    UPDATE CLIENTES
    SET NAME = @NAME, CARRERA = @CARRERA, TELEFONO = @TELEFONO, PHOTO = @PHOTO
    WHERE CODIGO = @CODIGO;
END
GO

IF OBJECT_ID('dbo.usp_QueryAllClientes', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryAllClientes;
GO
CREATE PROCEDURE usp_QueryAllClientes AS
BEGIN
    SELECT * FROM CLIENTES;
END
GO

IF OBJECT_ID('dbo.usp_QueryClientesId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryClientesId;
GO
CREATE PROCEDURE usp_QueryClientesId(
    @ID VARCHAR(100)
) AS
BEGIN
    SELECT * FROM CLIENTES
    WHERE CODIGO = @ID;
END
GO

IF OBJECT_ID('dbo.usp_DeleteClientes', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_DeleteClientes;
GO
CREATE PROCEDURE usp_DeleteClientes(
    @ID VARCHAR(100)
) AS
BEGIN
    DELETE FROM CLIENTES
    WHERE CODIGO = @ID;
END
GO

-- PROCEDURES FOR FAJAS
IF OBJECT_ID('dbo.usp_AddFajas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AddFajas;
GO
CREATE PROCEDURE usp_AddFajas(
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @ALTO_GOMA DECIMAL(10,2),
    @DIAMETRO_INTERNO DECIMAL(10,2),
    @DIAMETRO_EXTERNO DECIMAL(10,2)
) AS
BEGIN
    INSERT INTO FAJAS (NAME, CANTIDAD, PROVEEDOR, ALTO_GOMA, DIAMETRO_INTERNO, DIAMETRO_EXTERNO)
    VALUES (@NAME, @CANTIDAD, @PROVEEDOR, @ALTO_GOMA, @DIAMETRO_INTERNO, @DIAMETRO_EXTERNO);
END
GO

IF OBJECT_ID('dbo.usp_UpdateFajas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_UpdateFajas;
GO
CREATE PROCEDURE usp_UpdateFajas(
    @ID INT,
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @ALTO_GOMA DECIMAL(10,2),
    @DIAMETRO_INTERNO DECIMAL(10,2),
    @DIAMETRO_EXTERNO DECIMAL(10,2)
) AS
BEGIN
    UPDATE FAJAS
    SET NAME = @NAME, CANTIDAD = @CANTIDAD, PROVEEDOR = @PROVEEDOR,
        ALTO_GOMA = @ALTO_GOMA, DIAMETRO_INTERNO = @DIAMETRO_INTERNO, DIAMETRO_EXTERNO = @DIAMETRO_EXTERNO
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_QueryAllFajas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryAllFajas;
GO
CREATE PROCEDURE usp_QueryAllFajas AS
BEGIN
    SELECT * FROM FAJAS;
END
GO

IF OBJECT_ID('dbo.usp_QueryFajasId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryFajasId;
GO
CREATE PROCEDURE usp_QueryFajasId(
    @ID INT
) AS
BEGIN
    SELECT * FROM FAJAS
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_DeleteFajas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_DeleteFajas;
GO
CREATE PROCEDURE usp_DeleteFajas(
    @ID INT
) AS
BEGIN
    DELETE FROM FAJAS
    WHERE ID = @ID;
END
GO

-- PROCEDURES FOR POLEAS
IF OBJECT_ID('dbo.usp_AddPoleas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AddPoleas;
GO
CREATE PROCEDURE usp_AddPoleas(
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @DIAMETRO_INTERNO DECIMAL(10,2),
    @DIAMETRO_EXTERNO DECIMAL(10,2)
) AS
BEGIN
    INSERT INTO POLEAS (NAME, CANTIDAD, PROVEEDOR, DIAMETRO_INTERNO, DIAMETRO_EXTERNO)
    VALUES (@NAME, @CANTIDAD, @PROVEEDOR, @DIAMETRO_INTERNO, @DIAMETRO_EXTERNO);
END
GO

IF OBJECT_ID('dbo.usp_UpdatePoleas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_UpdatePoleas;
GO
CREATE PROCEDURE usp_UpdatePoleas(
    @ID INT,
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @DIAMETRO_INTERNO DECIMAL(10,2),
    @DIAMETRO_EXTERNO DECIMAL(10,2)
) AS
BEGIN
    UPDATE POLEAS
    SET NAME = @NAME, CANTIDAD = @CANTIDAD, PROVEEDOR = @PROVEEDOR,
        DIAMETRO_INTERNO = @DIAMETRO_INTERNO, DIAMETRO_EXTERNO = @DIAMETRO_EXTERNO
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_QueryAllPoleas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryAllPoleas;
GO
CREATE PROCEDURE usp_QueryAllPoleas AS
BEGIN
    SELECT * FROM POLEAS;
END
GO

IF OBJECT_ID('dbo.usp_QueryPoleasId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryPoleasId;
GO
CREATE PROCEDURE usp_QueryPoleasId(
    @ID INT
) AS
BEGIN
    SELECT * FROM POLEAS
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_DeletePoleas', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_DeletePoleas;
GO
CREATE PROCEDURE usp_DeletePoleas(
    @ID INT
) AS
BEGIN
    DELETE FROM POLEAS
    WHERE ID = @ID;
END
GO

-- PROCEDURES FOR TORNILLOS
IF OBJECT_ID('dbo.usp_AddTornillos', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AddTornillos;
GO
CREATE PROCEDURE usp_AddTornillos(
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @TIPO_PUNTA VARCHAR(100),
    @TIPO_ROSCA VARCHAR(100)
) AS
BEGIN
    INSERT INTO TORNILLOS (NAME, CANTIDAD, PROVEEDOR, TIPO_PUNTA, TIPO_ROSCA)
    VALUES (@NAME, @CANTIDAD, @PROVEEDOR, @TIPO_PUNTA, @TIPO_ROSCA);
END
GO

IF OBJECT_ID('dbo.usp_UpdateTornillos', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_UpdateTornillos;
GO
CREATE PROCEDURE usp_UpdateTornillos(
    @ID INT,
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @TIPO_PUNTA VARCHAR(100),
    @TIPO_ROSCA VARCHAR(100)
) AS
BEGIN
    UPDATE TORNILLOS
    SET NAME = @NAME, CANTIDAD = @CANTIDAD, PROVEEDOR = @PROVEEDOR,
        TIPO_PUNTA = @TIPO_PUNTA, TIPO_ROSCA = @TIPO_ROSCA
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_QueryAllTornillos', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryAllTornillos;
GO
CREATE PROCEDURE usp_QueryAllTornillos AS
BEGIN
    SELECT * FROM TORNILLOS;
END
GO

IF OBJECT_ID('dbo.usp_QueryTornillosId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryTornillosId;
GO
CREATE PROCEDURE usp_QueryTornillosId(
    @ID INT
) AS
BEGIN
    SELECT * FROM TORNILLOS
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_DeleteTornillos', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_DeleteTornillos;
GO
CREATE PROCEDURE usp_DeleteTornillos(
    @ID INT
) AS
BEGIN
    DELETE FROM TORNILLOS
    WHERE ID = @ID;
END
GO

-- PROCEDURES FOR MOTORESAC
IF OBJECT_ID('dbo.usp_AddMotoresAC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AddMotoresAC;
GO
CREATE PROCEDURE usp_AddMotoresAC(
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @FRAME DECIMAL(10,2),
    @POTENCIA DECIMAL(10,2),
    @FASES VARCHAR(100)
) AS
BEGIN
    INSERT INTO MOTORESAC (NAME, CANTIDAD, PROVEEDOR, FRAME, POTENCIA, FASES)
    VALUES (@NAME, @CANTIDAD, @PROVEEDOR, @FRAME, @POTENCIA, @FASES);
END
GO

IF OBJECT_ID('dbo.usp_UpdateMotoresAC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_UpdateMotoresAC;
GO
CREATE PROCEDURE usp_UpdateMotoresAC(
    @ID INT,
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @FRAME DECIMAL(10,2),
    @POTENCIA DECIMAL(10,2),
    @FASES VARCHAR(100)
) AS
BEGIN
    UPDATE MOTORESAC
    SET NAME = @NAME, CANTIDAD = @CANTIDAD, PROVEEDOR = @PROVEEDOR,
        FRAME = @FRAME, POTENCIA = @POTENCIA, FASES = @FASES
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_QueryAllMotoresAC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryAllMotoresAC;
GO
CREATE PROCEDURE usp_QueryAllMotoresAC AS
BEGIN
    SELECT * FROM MOTORESAC;
END
GO

IF OBJECT_ID('dbo.usp_QueryMotoresACId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryMotoresACId;
GO
CREATE PROCEDURE usp_QueryMotoresACId(
    @ID INT
) AS
BEGIN
    SELECT * FROM MOTORESAC
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_DeleteMotoresAC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_DeleteMotoresAC;
GO
CREATE PROCEDURE usp_DeleteMotoresAC(
    @ID INT
) AS
BEGIN
    DELETE FROM MOTORESAC
    WHERE ID = @ID;
END
GO

-- PROCEDURES FOR MOTORESDC
IF OBJECT_ID('dbo.usp_AddMotoresDC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_AddMotoresDC;
GO
CREATE PROCEDURE usp_AddMotoresDC(
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @VOLTAJE DECIMAL(10,2),
    @POTENCIA DECIMAL(10,2),
    @VELOCIDAD DECIMAL(10,2)
) AS
BEGIN
    INSERT INTO MOTORESDC (NAME, CANTIDAD, PROVEEDOR, VOLTAJE, POTENCIA, VELOCIDAD)
    VALUES (@NAME, @CANTIDAD, @PROVEEDOR, @VOLTAJE, @POTENCIA, @VELOCIDAD);
END
GO

IF OBJECT_ID('dbo.usp_UpdateMotoresDC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_UpdateMotoresDC;
GO
CREATE PROCEDURE usp_UpdateMotoresDC(
    @ID INT,
    @NAME VARCHAR(200),
    @CANTIDAD VARCHAR(400),
    @PROVEEDOR VARCHAR(100),
    @VOLTAJE DECIMAL(10,2),
    @POTENCIA DECIMAL(10,2),
    @VELOCIDAD DECIMAL(10,2)
) AS
BEGIN
    UPDATE MOTORESDC
    SET NAME = @NAME, CANTIDAD = @CANTIDAD, PROVEEDOR = @PROVEEDOR,
        VOLTAJE = @VOLTAJE, POTENCIA = @POTENCIA, VELOCIDAD = @VELOCIDAD
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_QueryAllMotoresDC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryAllMotoresDC;
GO
CREATE PROCEDURE usp_QueryAllMotoresDC AS
BEGIN
    SELECT * FROM MOTORESDC;
END
GO

IF OBJECT_ID('dbo.usp_QueryMotoresDCId', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_QueryMotoresDCId;
GO
CREATE PROCEDURE usp_QueryMotoresDCId(
    @ID INT
) AS
BEGIN
    SELECT * FROM MOTORESDC
    WHERE ID = @ID;
END
GO

IF OBJECT_ID('dbo.usp_DeleteMotoresDC', 'P') IS NOT NULL
    DROP PROCEDURE dbo.usp_DeleteMotoresDC;
GO
CREATE PROCEDURE usp_DeleteMotoresDC(
    @ID INT
) AS
BEGIN
    DELETE FROM MOTORESDC
    WHERE ID = @ID;
END
GO
