-- Eliminar tablas existentes si existen
IF OBJECT_ID('dbo.EMPLEADO', 'U') IS NOT NULL DROP TABLE EMPLEADO;
IF OBJECT_ID('dbo.CLIENTE', 'U') IS NOT NULL DROP TABLE CLIENTE;

CREATE TABLE CLIENTE (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CODIGO INT NOT NULL,
    DNI INT NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    STATUS CHAR(1) NULL,
    TELEFONO INT NOT NULL,
    PHOTO IMAGE NULL,
    ISCORP CHAR(1) NULL,
    ISFREQUENT CHAR(1) NULL,
    CURSO VARCHAR(50) NULL,
    CARRERA VARCHAR(100) NULL
);

CREATE TABLE EMPLEADO (
    ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CODIGO INT NOT NULL,
    DNI INT NOT NULL, 
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    STATUS CHAR(1) NULL,
    TELEFONO INT NOT NULL,
    PHOTO IMAGE NULL,
    QUOTA DECIMAL(10,2) NULL,
    SALES DECIMAL(10,2) NULL,
    WORKHOURS DECIMAL(10,2) NULL,
    SALARY DECIMAL(10,2) NULL,
    WARNINGS VARCHAR(300) NULL,
    TURNO VARCHAR(50) NULL,
    I_CONTRATO DATETIME,
    F_CONTRATO DATETIME
);

-- Eliminar y crear procedimientos almacenados para CLIENTE

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_QueryClienteByName]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryClienteByName]
END
GO

CREATE PROCEDURE dbo.usp_QueryClienteByName (@NAME VARCHAR(100)) AS 
BEGIN
    SELECT * 
    FROM CLIENTE 
    WHERE NAME = @NAME
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_QueryClienteById]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryClienteById]
END
GO

CREATE PROCEDURE dbo.usp_QueryClienteById (@ID INT) AS 
BEGIN
    SELECT * 
    FROM CLIENTE 
    WHERE ID = @ID
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_AddCliente]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_AddCliente]
END
GO

CREATE PROCEDURE dbo.usp_AddCliente (
    @CODIGO INT,
    @DNI INT,
    @USERNAME VARCHAR(100),
    @PASSWORD VARCHAR(100),
    @NAME VARCHAR(100),
    @LASTNAME VARCHAR(100),
    @STATUS CHAR(1),
    @TELEFONO INT,
    @PHOTO IMAGE,
    @ISCORP CHAR(1),
    @ISFREQUENT CHAR(1),
    @CURSO VARCHAR(50),
    @CARRERA VARCHAR(100),
    @ID INT OUTPUT
) AS
BEGIN
    INSERT INTO CLIENTE (CODIGO, DNI, USERNAME, PASSWORD, NAME, LASTNAME, STATUS, TELEFONO, PHOTO, ISCORP, ISFREQUENT, CURSO, CARRERA)
    VALUES (@CODIGO, @DNI, @USERNAME, @PASSWORD, @NAME, @LASTNAME, @STATUS, @TELEFONO, @PHOTO, @ISCORP, @ISFREQUENT, @CURSO, @CARRERA)

    SET @ID = SCOPE_IDENTITY()
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_DeleteCliente]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_DeleteCliente]
END
GO

CREATE PROCEDURE dbo.usp_DeleteCliente (@ID INT) AS
BEGIN
    DELETE FROM CLIENTE WHERE ID = @ID
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_UpdateCliente]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_UpdateCliente]
END
GO

CREATE PROCEDURE dbo.usp_UpdateCliente (
    @ID INT,
    @CODIGO INT,
    @DNI INT,
    @USERNAME VARCHAR(100),
    @PASSWORD VARCHAR(100),
    @NAME VARCHAR(100),
    @LASTNAME VARCHAR(100),
    @STATUS CHAR(1),
    @TELEFONO INT,
    @PHOTO IMAGE,
    @ISCORP CHAR(1),
    @ISFREQUENT CHAR(1),
    @CURSO VARCHAR(50),
    @CARRERA VARCHAR(100)
) AS
BEGIN
    UPDATE CLIENTE
    SET CODIGO = @CODIGO, DNI = @DNI, USERNAME = @USERNAME, PASSWORD = @PASSWORD, NAME = @NAME, LASTNAME = @LASTNAME, 
        STATUS = @STATUS, TELEFONO = @TELEFONO, PHOTO = @PHOTO, ISCORP = @ISCORP, ISFREQUENT = @ISFREQUENT, 
        CURSO = @CURSO, CARRERA = @CARRERA
    WHERE ID = @ID
END
GO

-- Procedimiento para consultar todos los clientes
IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_QueryAllClientes]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryAllClientes]
END
GO

CREATE PROCEDURE dbo.usp_QueryAllClientes AS 
BEGIN
    SELECT * FROM CLIENTE
END
GO

-- Eliminar y crear procedimientos almacenados para EMPLEADO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_QueryEmpleadoByName]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryEmpleadoByName]
END
GO

CREATE PROCEDURE dbo.usp_QueryEmpleadoByName (@NAME VARCHAR(100)) AS 
BEGIN
    SELECT * 
    FROM EMPLEADO 
    WHERE NAME = @NAME
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_QueryEmpleadoById]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryEmpleadoById]
END
GO

CREATE PROCEDURE dbo.usp_QueryEmpleadoById (@ID INT) AS 
BEGIN
    SELECT * 
    FROM EMPLEADO 
    WHERE ID = @ID
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_AddEmpleado]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_AddEmpleado]
END
GO

CREATE PROCEDURE dbo.usp_AddEmpleado (
    @CODIGO INT,
    @DNI INT,
    @USERNAME VARCHAR(100),
    @PASSWORD VARCHAR(100),
    @NAME VARCHAR(100),
    @LASTNAME VARCHAR(100),
    @STATUS CHAR(1),
    @TELEFONO INT,
    @PHOTO IMAGE,
    @QUOTA DECIMAL(10,2),
    @SALES DECIMAL(10,2),
    @WORKHOURS DECIMAL(10,2),
    @SALARY DECIMAL(10,2),
    @WARNINGS VARCHAR(300),
    @TURNO VARCHAR(50),
	@I_CONTRATO DATETIME,
	@F_CONTRATO DATETIME,
    @ID INT OUTPUT
) AS
BEGIN
    INSERT INTO EMPLEADO (CODIGO, DNI, USERNAME, PASSWORD, NAME, LASTNAME, STATUS, TELEFONO, PHOTO, QUOTA, SALES, WORKHOURS, SALARY, WARNINGS, TURNO,I_CONTRATO,F_CONTRATO )
    VALUES (@CODIGO, @DNI, @USERNAME, @PASSWORD, @NAME, @LASTNAME, @STATUS, @TELEFONO, @PHOTO, @QUOTA, @SALES, @WORKHOURS, @SALARY, @WARNINGS, @TURNO,@I_CONTRATO,@F_CONTRATO )

    SET @ID = SCOPE_IDENTITY()
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_DeleteEmpleado]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_DeleteEmpleado]
END
GO

CREATE PROCEDURE dbo.usp_DeleteEmpleado (@ID INT) AS
BEGIN
    DELETE FROM EMPLEADO WHERE ID = @ID
END
GO

IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_UpdateEmpleado]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_UpdateEmpleado]
END
GO

CREATE PROCEDURE dbo.usp_UpdateEmpleado (
    @ID INT,
    @CODIGO INT,
    @DNI INT,
    @USERNAME VARCHAR(100),
    @PASSWORD VARCHAR(100),
    @NAME VARCHAR(100),
    @LASTNAME VARCHAR(100),
    @STATUS CHAR(1),
    @TELEFONO INT,
    @PHOTO IMAGE,
    @QUOTA DECIMAL(10,2),
    @SALES DECIMAL(10,2),
    @WORKHOURS DECIMAL(10,2),
    @SALARY DECIMAL(10,2),
    @WARNINGS VARCHAR(300),
    @TURNO VARCHAR(50),
    @I_CONTRATO DATETIME,
    @F_CONTRATO DATETIME
) AS
BEGIN
    UPDATE EMPLEADO
    SET CODIGO = @CODIGO, DNI = @DNI, USERNAME = @USERNAME, PASSWORD = @PASSWORD, NAME = @NAME, LASTNAME = @LASTNAME, 
        STATUS = @STATUS, TELEFONO = @TELEFONO, PHOTO = @PHOTO, QUOTA = @QUOTA, SALES = @SALES, WORKHOURS = @WORKHOURS, 
        SALARY = @SALARY, WARNINGS = @WARNINGS, TURNO = @TURNO, I_CONTRATO = @I_CONTRATO, F_CONTRATO = @F_CONTRATO
    WHERE ID = @ID
END
GO

-- Procedimiento para consultar todos los empleados
IF EXISTS (SELECT * FROM sysobjects WHERE id = object_id(N'[dbo].[usp_QueryAllEmpleados]') AND OBJECTPROPERTY(id, N'IsProcedure') = 1)
BEGIN
    DROP PROCEDURE [dbo].[usp_QueryAllEmpleados]
END
GO

CREATE PROCEDURE dbo.usp_QueryAllEmpleados AS 
BEGIN
    SELECT * FROM EMPLEADO
END
GO
